language: cpp
compiler: 
    - clang
notifications:
    email: false
env:
    matrix: 
        - JULIAVERSION="julianightlies" 
before_install:
    - sudo add-apt-repository ppa:staticfloat/julia-deps -y
    - sudo add-apt-repository ppa:staticfloat/${JULIAVERSION} -y
    - sudo apt-get update -qq -y
    - sudo apt-get install libpcre3-dev julia -y
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
script:
    - julia -e 'Pkg.init(); Pkg.clone(pwd()); Pkg.test("Dates")'
    - julia -e 'using Dates; @assert isdefined(:Dates); @assert typeof(Dates) === Module'
    - if [ $JULIAVERSION = "julianightlies" ]; then julia --code-coverage test/runtests.jl; fi
after_success:
    - if [ $JULIAVERSION = "julianightlies" ]; then julia -e 'cd(Pkg.dir("Dates")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi